services:
  order-db:
    image: postgres:15
    container_name: order-db
    restart: always
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - orders-data:/var/lib/postgresql/data
      - ./sql/init_order.sql:/docker-entrypoint-initdb.d/init_orders.sql:ro
  inventory-db:
    image: postgres:15
    container_name: inventory-db
    restart: always
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - inventory-data:/var/lib/postgresql/data
      - ./sql/init_inventory.sql:/docker-entrypoint-initdb.d/init_inventory.sql:ro
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - order-db
      - inventory-db
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
volumes:
  orders-data:
  inventory-data:
