syntax = "proto3";

package inventory;
option go_package = ".;proto";

enum InventoryStatus {
    RESERVED = 0;
    FAILED = 1;
}

enum FailureReason {
    OUT_OF_STOCK = 0;
    SYSTEM_ERROR = 1;
}

message InventoryReserved {
  string order_id = 1;
  string product_id = 2;
  int32 quantity = 3;
  int64 timestamp = 4; // Unix epoch millis
  InventoryStatus status = 5; // should be RESERVED
}

message InventoryFailed {
  string order_id = 1;
  string product_id = 2;
  int32 quantity = 3;
  int64 timestamp = 4; // Unix epoch millis
  InventoryStatus status = 5; // should be FAILED
  FailureReason reason = 6;
}